#!/usr/bin/env python3
"""Generate drupal-fragment.html from index.html.

index.html is the single source of truth. The fragment is derived, never edited
by hand — that is the whole point of this script. The sibling AI Risk Framework
kept a hand-maintained Drupal copy and the two drifted; don't repeat it.

    python3 build-fragment.py            # write drupal-fragment.html
    python3 build-fragment.py --check    # exit 1 if the fragment is stale

What it does: keeps the two <style> blocks and everything inside the
.lu-advisor wrapper, and drops the page shell (doctype/html/head/body) plus the
Google Fonts <link>, which a Drupal page supplies itself.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "index.html"
OUT = HERE / "drupal-fragment.html"

HEADER = """<!-- ============================================================
     AI Tool Advisor - Drupal fragment
     GENERATED by build-fragment.py from index.html. Do not edit directly;
     edit index.html and re-run the script.

     Paste with the "Full HTML" text format via the source/code view.
     CKEditor's visual editor strips <style> and <script>.

     Self-contained: no CDN stylesheets or scripts. Dopis is fetched from
     lehigh.edu, which serves it with Access-Control-Allow-Origin: *, so it
     resolves from any origin. If those URLs ever 404, the stacks fall back to
     Sora and then to the host page's serif.

     All CSS is scoped to .lu-advisor and every id is prefixed luadv-, so the
     widget and the site theme cannot restyle each other. Layout responds to the
     width of the region it is pasted into via container queries, not to the
     viewport, so it behaves in a narrow content column.

     One thing to decide on paste: the widget's title is an <h1>. A Drupal page
     usually supplies its own <h1>, so demote it to <h2> to keep the heading
     order valid. The styling is class-based (.adv-title), so nothing else
     changes.
     ============================================================ -->
"""


def build(src: str) -> str:
    styles = re.findall(r"<style>(.*?)</style>", src, re.S)
    if len(styles) < 2:
        sys.exit("error: expected two <style> blocks (@font-face, then scoped rules)")

    m = re.search(
        r'<div class="lu-advisor" id="luadv-root">\n(.*)\n</div><!-- /\.lu-advisor -->',
        src,
        re.S,
    )
    if not m:
        sys.exit("error: could not find the .lu-advisor wrapper in index.html")

    return (
        HEADER
        + '<div class="lu-advisor" id="luadv-root">\n<style>\n'
        + styles[0]
        + styles[-1]
        + "</style>\n"
        + m.group(1)
        + "\n</div>\n"
    )


def verify(fragment: str) -> list:
    """Catch the mistakes that make a fragment unusable in a CMS."""
    problems = []
    low = fragment.lower()
    for tag in ("<!doctype", "<html", "<head>", "<body"):
        if tag in low:
            problems.append(f"page-level tag present: {tag}")
    for dep in re.findall(r'<(?:link|script)[^>]*(?:href|src)="https?://[^"]+"', fragment):
        problems.append(f"external asset dependency: {dep[:70]}")
    if "container-type" not in fragment:
        problems.append("no container-type — layout would key off the viewport")
    # every rule should be scoped; @font-face and at-rule wrappers are exempt
    css = "".join(re.findall(r"<style>(.*?)</style>", fragment, re.S))
    for line in css.split("\n"):
        s = line.strip()
        if not s or s.startswith(("@", "/*", "*", "}")) or "{" not in s:
            continue
        sel = s.split("{")[0].strip()
        if sel and not sel.startswith(".lu-advisor") and ":" not in sel:
            problems.append(f"unscoped selector: {sel[:50]}")
    return problems


def main() -> int:
    fragment = build(SRC.read_text())
    problems = verify(fragment)

    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != fragment:
            print("STALE: drupal-fragment.html does not match index.html")
            print("  run: python3 build-fragment.py")
            return 1
        if problems:
            print("fragment is current but has problems:")
            for p in problems:
                print("  -", p)
            return 1
        print(f"drupal-fragment.html is current and clean ({len(fragment):,} bytes)")
        return 0

    OUT.write_text(fragment)
    print(f"wrote {OUT.name} ({len(fragment):,} bytes)")
    if problems:
        print("problems found:")
        for p in problems:
            print("  -", p)
        return 1
    print("checks passed: no page-level tags, no external assets, all rules scoped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
